=== anteq/pm-cli/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "PM CLI schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "additionalProperties": true,
    "required": [
        "reporter",
        "defaults",
        "projects",
        "people"
    ],
    "properties": {
        "reporter": {
            "$id": "#/properties/reporter",
            "type": "string",
            "title": "Reporter",
            "description": "Key of default task reported in JIRA.",
            "default": "",
            "examples": [
                "antek"
            ]
        },
        "defaults": {
            "$id": "#/properties/defaults",
            "type": "object",
            "title": "Defaults",
            "description": "Defaults values",
            "default": {
                "issuetype": "task",
                "priority": "major"
            },
            "examples": [
                {
                    "issuetype": "bug",
                    "priority": "minor"
                }
            ],
            "additionalProperties": true,
            "properties": {
                "issuetype": {
                    "$id": "#/properties/defaults/properties/issuetype",
                    "type": "string",
                    "title": "Issue Type",
                    "description": "Key of default issue type",
                    "default": "task"
                },
                "priority": {
                    "$id": "#/properties/defaults/properties/priority",
                    "type": "string",
                    "title": "Priority",
                    "description": "Key of default priority",
                    "default": "major"
                }
            }
        },
        "projects": {
            "$id": "#/properties/projects",
            "type": "array",
            "title": "Projects",
            "description": "Defines JIRA projects that are to be supported.",
            "default": [],
            "examples": [
                [
                    {
                        "key": "sp",
                        "name": "Sample Project",
                        "jiraRapidViewId": 15,
                        "baseUrl": "https://sample-project.atlassian.net",
                        "jiraId": 10000
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/projects/items",
                "type": "object",
                "title": "Items",
                "description": "",
                "default": {},
                "examples": [
                    {
                        "key": "sp",
                        "name": "Sample Project",
                        "jiraRapidViewId": 15,
                        "baseUrl": "https://sample.atlassian.net",
                        "jiraId": 10000
                    }
                ],
                "additionalProperties": true,
                "required": [
                    "key",
                    "name",
                    "jiraId",
                    "jiraRapidViewId",
                    "baseUrl"
                ],
                "properties": {
                    "key": {
                        "$id": "#/properties/projects/items/properties/key",
                        "type": "string",
                        "title": "Key",
                        "description": "JIRA key that identifies this project. If your issues follow the convention SP-1000, then your key is SP.",
                        "default": "",
                        "examples": [
                            "sp"
                        ]
                    },
                    "name": {
                        "$id": "#/properties/projects/items/properties/name",
                        "type": "string",
                        "title": "Name",
                        "description": "Name of your project.",
                        "default": "",
                        "examples": [
                            "Tagger Product"
                        ]
                    },
                    "jiraId": {
                        "$id": "#/properties/projects/items/properties/jiraId",
                        "type": "integer",
                        "title": "Jira ID",
                        "description": "JIRA ID of your project.",
                        "default": 0,
                        "examples": [
                            10500
                        ]
                    },
                    "jiraRapidViewId": {
                        "$id": "#/properties/projects/items/properties/jiraRapidViewId",
                        "type": "integer",
                        "title": "JIRA Rapid View ID",
                        "description": "JIRA Rapid View ID of your project. Used to access Backlog and Active Sprints view.",
                        "default": 0,
                        "examples": [
                            15
                        ]
                    },
                    "baseUrl": {
                        "$id": "#/properties/projects/items/properties/baseUrl",
                        "type": "string",
                        "title": "Base URL",
                        "description": "URL to your JIRA instance, without trailing slashes.",
                        "default": "",
                        "examples": [
                            "https://sample.atlassian.net"
                        ]
                    }
                }
            }
        },
        "people": {
            "$id": "#/properties/people",
            "type": "array",
            "title": "People",
            "description": "Your team members.",
            "default": [],
            "examples": [
                [
                    {
                        "triggers": [
                            "anna"
                        ],
                        "jiraId": "5d92f3a91d47a50c34d4c073",
                        "key": "tom",
                        "name": "Tomasz"
                    },
                    {
                        "key": "antek",
                        "name": "Antek",
                        "jiraId": "5a299213301ed0381f22a9a1"
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/people/items",
                "type": "object",
                "title": "Items",
                "description": "",
                "default": {},
                "examples": [
                    {
                        "triggers": [
                            "tomek"
                        ],
                        "jiraId": "5d92f3a91d47a50c34d4c073",
                        "key": "tom",
                        "name": "Tomasz"
                    },
                    {
                        "key": "antek",
                        "name": "Antek G",
                        "jiraId": "5a299213301ed0381f22a9a1"
                    }
                ],
                "additionalProperties": true,
                "required": [
                    "key",
                    "name",
                    "jiraId"
                ],
                "properties": {
                    "key": {
                        "$id": "#/properties/people/items/properties/key",
                        "type": "string",
                        "title": "Key",
                        "description": "Internal key used to identify this person.",
                        "default": "",
                        "examples": [
                            "antek"
                        ]
                    },
                    "name": {
                        "$id": "#/properties/people/items/properties/name",
                        "type": "string",
                        "title": "Name",
                        "description": "Person's name.",
                        "default": "",
                        "examples": [
                            "Antek G"
                        ]
                    },
                    "triggers": {
                        "$id": "#/properties/people/items/properties/triggers",
                        "type": "array",
                        "title": "Triggers",
                        "description": "Extra triggers for this person e.g. nicknames, abbreviations. Key is also used in search here.",
                        "default": [],
                        "examples": [
                            [
                                "anti",
                                "anton"
                            ]
                        ],
                        "additionalItems": true,
                        "items": {
                            "$id": "#/properties/people/items/properties/triggers/items",
                            "type": "string",
                            "title": "Items",
                            "description": "",
                            "default": "",
                            "examples": [
                                "anti",
                                "anton"
                            ]
                        }
                    },
                    "jiraId": {
                        "$id": "#/properties/projects/items/properties/jiraId",
                        "type": "string",
                        "title": "Jira ID",
                        "description": "JIRA ID of this person",
                        "default": "",
                        "examples": [
                            "5d92f3a91d47a50c34d4c073"
                        ]
                    }
                }
            }
        },
        "custom": {
            "$id": "#/properties/custom",
            "type": "array",
            "title": "Custom triggers",
            "description": "Add custom triggers for any URL.",
            "default": [],
            "examples": [
                [
                    {
                        "triggers": [
                            "jenkins",
                            "build"
                        ],
                        "url": "http://jenkins.tagger.lan",
                        "key": "jenkins",
                        "name": "Jenkins"
                    },
                    {
                        "url": "https://app.taggermedia.com/profile/344913",
                        "key": "google",
                        "name": "Google",
                        "triggers": [
                            "search",
                            "google"
                        ]
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/custom/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": {},
                "examples": [
                    {
                        "triggers": [
                            "jenkins",
                            "build"
                        ],
                        "url": "http://jenkins.com",
                        "key": "jenkins",
                        "name": "Jenkins"
                    },
                    {
                        "url": "https://app.taggermedia.com/profile/344913",
                        "key": "julia",
                        "name": "Julia Engel in Tagger",
                        "triggers": [
                            "julia",
                            "tagger julia"
                        ]
                    },
                    {
                        "triggers": [
                            "justin",
                            "tagger justin"
                        ],
                        "url": "https://app.taggermedia.com/profile/80",
                        "key": "justin",
                        "name": "Justin Bieber in Tagger"
                    }
                ],
                "additionalProperties": true,
                "required": [
                    "key",
                    "name",
                    "triggers",
                    "url"
                ],
                "properties": {
                    "key": {
                        "$id": "#/properties/people/items/properties/key",
                        "type": "string",
                        "title": "Key",
                        "description": "Internal key used to identify this url.",
                        "default": "",
                        "examples": [
                            "jenkins"
                        ]
                    },
                    "name": {
                        "$id": "#/properties/custom/items/properties/name",
                        "type": "string",
                        "title": "Name",
                        "description": "Display name for url.",
                        "default": "",
                        "examples": [
                            "Jenkins"
                        ]
                    },
                    "triggers": {
                        "$id": "#/properties/custom/items/properties/triggers",
                        "type": "array",
                        "title": "Triggers",
                        "description": "Triggers for this url e.g. names, abbreviations. Key is *not* used by default here.",
                        "default": [],
                        "examples": [
                            [
                                "jenkins",
                                "build"
                            ]
                        ],
                        "additionalItems": true,
                        "items": {
                            "$id": "#/properties/custom/items/properties/triggers/items",
                            "type": "string",
                            "title": "Items",
                            "description": "",
                            "default": "",
                            "examples": [
                                "jenkins",
                                "build"
                            ]
                        }
                    },
                    "url": {
                        "$id": "#/properties/custom/items/properties/url",
                        "type": "string",
                        "title": "Url",
                        "description": "Specifies where to route when the trigger is hit.",
                        "default": "",
                        "examples": [
                            "http://jenkins.com"
                        ]
                    }
                }
            }
        }
    }
}

=== anteq/pm-cli/config.json
{
    "reporter": "antek",
    "defaults": {
        "issuetype": "task",
        "priority": "major"
    },
    "projects": [
        {
            "key": "pt",
            "name": "Tagger Product",
            "jiraId": 10500,
            "jiraRapidViewId": 15,
            "baseUrl": "https://scalaric.atlassian.net"
        },
        {
            "key": "tm",
            "name": "Tagger",
            "jiraId": 10200,
            "jiraRapidViewId": 8,
            "baseUrl": "https://scalaric.atlassian.net"
        }
    ],
    "people": [
        {
            "key": "ania",
            "name": "Ania Oruba",
            "triggers": ["anna"],
            "jiraId": "5d92f3a91d47a50c34d4c073"
        },
        {
            "key": "antek",
            "name": "Antek Grzanka",
            "jiraId": "5a299213301ed0381f22a9a1"
        },
        {
            "key": "bartek",
            "name": "Bartek Radziszewski",
            "jiraId": "557058:512b8678-e90f-43b9-a143-ee74268ae31a"
        },
        {
            "key": "kacper",
            "name": "Kacper Bieda",
            "jiraId": "5bfbd8d2c22785142f67d695"
        },
        {
            "key": "konrad",
            "name": "Konrad Dzikowski",
            "jiraId": "5da4173b5f18bb0c40fec013"
        },
        {
            "key": "krzysiek",
            "name": "Krzysztof Kardaś",
            "triggers": ["krz", "krzysztof"],
            "jiraId": "5c53f2c261740840d4e6cc8f"
        },
        {
            "key": "matt",
            "name": "Matt Ginn",
            "jiraId": "5bfbd8e2a391f63e5a27de05"
        },
        {
            "key": "marnik",
            "name": "Piotr Marnik",
            "triggers": ["pm"],
            "jiraId": "5bfbd8eddda509509754a751"
        },
        {
            "key": "mlody",
            "name": "Piotr Radziszewski",
            "triggers": ["młody", "pr"],
            "jiraId": "5bfbd8e85e2eee35d79f573e"
        },
        {
            "key": "wos",
            "name": "Piotr Woś",
            "triggers": ["pw", "woś"],
            "jiraId": "5c8768de677d763daafa494b"
        },
        {
            "key": "tomek",
            "name": "Tomasz Bogusiak",
            "triggers": ["tom", "tomasz"],
            "jiraId": "5c53f2c00e5b0669d85a3967"
        },
        {
            "key": "wojtek",
            "name": "Wojciech Janoszek",
            "triggers": ["woj", "wojciech"],
            "jiraId": "5da4173a260e4d0c422332f9"
        }
    ],
    "custom": [
        {
            "key": "jenkins",
            "name": "Jenkins",
            "triggers": ["jenkins", "build"],
            "url": "http://jenkins.tagger.lan"
        },
        {
            "key": "julia",
            "name": "Julia Engel in Tagger",
            "triggers": ["julia", "tagger julia"],
            "url": "https://app.taggermedia.com/profile/344913"
        },
        {
            "key": "justin",
            "name": "Justin Bieber in Tagger",
            "triggers": ["justin", "tagger justin"],
            "url": "https://app.taggermedia.com/profile/80"
        }
    ]
}
